{{- with .Values.apiService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.name}}
  name: {{ $.Release.Name }}-{{.name}}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{.name}}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.images.api.repository }}:{{ $.Values.images.api.tag }}          
          envFrom:
            {{ toYaml .envFrom | nindent 12}}
          resources: {}      
status: {}
{{- end }}
