{{- with .Values.apiService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.name}}
  name: {{ $.Release.Name }}-{{.name}}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{.name}}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: {{ .name }}
          images: {{ $.Values.images.api.repository }}:{{ $.Values.images.api.tag }}          
          envFrom:
            - configMapRef:
                name: {{ .name }}-config
            {{- if eq $.Values.cloudProvider "aws"}}
            - secretRef:
                name: {{ .name }}-secret
            {{- end}}
          resources: {}      
status: {}
{{- end }}
