apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.workerService.name }}-config
data:
  {{- include "connection" $  | indent 2}}
  {{- with .Values.workerService.config -}}
    {{ toYaml . | nindent 2}}
  {{- end }}