{{- with .Values.workerService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .name }}
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          {{- with $.Values.images }}            
          image: {{ .worker.repository }}:{{ .worker.tag }}  
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}          
          envFrom:
            {{- toYaml .envFrom | nindent 12 }}            
          resources: {}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
status: {}
{{- end }}