{{- if .Values.workerService.pvcProvisioned }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workerService.name }}-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
