{{- if .Values.workerService.secret.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.workerService.name }}-secret
type: Opaque
stringData:
  {{- toYaml .Values.workerService.secret.data | nindent 2 }}
{{- end}}
