{{- if ne .Values.cloudProvider "local"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.workerService.name }}-secret
type: Opaque
stringData:
{{- if eq .Values.cloudProvider "aws" }}
  AWS_SECRET_ACCESS_KEY: test
{{- else if eq .Values.cloudProvider "gcp" }}
  key.json: {{ .Values.workerService.gcsKeyJson | quote }}
{{- end }}
{{- end}}
