{{- with .Values.mongoDBService }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
      component: database  
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .name }}
        component: database           
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: {{ $.Values.images.mongodb.repository }}:{{ $.Values.images.mongodb.tag }}
          ports:
            - containerPort: {{ .databasePort}}
              name: mongo-server
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .dbName }}
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
{{- end -}}