apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ministack-pvc
  namespace: default
  labels:
    app: ministack-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
