apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-worker-config
data:
  STORAGE_PROVIDER: gcs
  GCS_PROJECT_ID: "job-service-504018"
  GCS_KEY_FILE: "/var/secrets/gcs/key.json"
  S3_ENDPOINT: null
  AWS_REGION: null
  AWS_ACCESS_KEY_ID: null
