apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: job-service-worker-secret
    behavior: merge
    files:
      - key.json

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: ConfigMap
      name: job-service-worker-config
    path: configmap-patch.yaml
  - target:
      kind: Secret
      name: job-service-worker-secret
    path: secret-patch.yaml
  - target:
      kind: Deployment
      name: job-service-worker
    path: deployment-patch.yaml
