apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb/service.yaml
  - mongodb/statefulset.yaml

  - redis/pvc.yaml
  - redis/service.yaml
  - redis/deployment.yaml

  - ministack/secret.yaml
  - ministack/configmap.yaml
  - ministack/pvc.yaml
  - ministack/service.yaml
  - ministack/deployment.yaml

  - worker/configmap.yaml
  - worker/secret.yaml
  - worker/deployment.yaml

  - api/configmap.yaml
  - api/secret.yaml
  - api/service.yaml
  - api/deployment.yaml
  - api/ingress.yaml
