apiService:
  name: job-service-api  
  replicas: 2
  servicePort: 6500
  loadBalancer: false
  ingress:
    enabled: false
  secret:
    enabled: false
  envFrom:
    - configMapRef:
        name: job-service-api-config    

workerService:
  name: job-service-worker
  replicas: 2 
  envFrom:
    - configMapRef:
        name: job-service-worker-config
  config:
    STORAGE_PROVIDER: 
  pvcProvisioned: false
  secret:
    enabled: false
    data:

redisService:
  name: redis
  replicas: 1  
  redisPort: 6379

mongoDBService:
  name: mongodb  
  databasePort: 27017
  dbName: job-service
  replicas: 1

images:
  api:      
    repository: job-service-api
    tag: 1.0
  worker:      
    repository: job-service-worker
    tag: 1.0  
  redis: 
    repository: redis
    tag: 7.4-alpine
  mongodb:
    repository: mongo
    tag: 8.0.13