apiVersion: v1
kind: Service
metadata:
  labels:
    app: ministack
  name: ministack
spec:
  ports:
  - port: 4566
    protocol: TCP
    targetPort: 4566
  selector:
    app: ministack
  type: ClusterIP
status:
  loadBalancer: {}
