{{- with .Values.redisService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: redis
          image: {{ $.Values.images.redis.repository }}:{{ $.Values.images.redis.tag }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .redisPort }}
          volumeMounts:
            - name: {{ .name }}-data
              mountPath: /data
      volumes:
        - name: {{ .name }}-data
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
{{- end }}