apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-worker-config
data:
  REDIS_URL: redis://redis:6379
  MONGO_URL: mongodb://mongodb:27017/job-service
  S3_ENDPOINT: ministack
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: test
